=== tomaspineiro/Backup_Tool/devices/devices.dtd
<!ELEMENT devices (device*)>
<!ELEMENT device (name, address, username, password, backup_directory?)>
<!ATTLIST device type (switch|router|server) #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address EMPTY>
<!ATTLIST address mask CDATA #REQUIRED>
<!ATTLIST address ip CDATA #REQUIRED>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT backup_directory (#PCDATA)>

=== tomaspineiro/Backup_Tool/devices/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices SYSTEM "devices.dtd">
<!-- 
<devices>
  <device typo=(switch|router|server)>
    <name>name_divice</name>
    <address mask="1-34" ip="0.0.0.0" />
    <username>user_divice</username>
    <password>password_divice</password>
    <backup_directory>/path/to/backup/directory/switch1</backup_directory>
  </device>
</devices>  
-->
<devices>
  <device type="switch">
    <name>switch1</name>
    <address mask="24" ip="" />
    <username>admin</username>
    <password></password>
    <backup_directory>/path/to/backup/directory/switch1</backup_directory>
  </device>
  <device type="server">
    <name>serverFTP</name>
    <address mask="25" ip="..." />
    <username></username>
    <password></password>
  </device>
</devices>
